export const PAGE_NUMBER = 4;
export const LIMIT_PER_PAGE = 50;
export const IDS_PER_REQUEST = 50;
export const API_URL = 'https://www.googleapis.com/youtube/v3/';

export const SEARCH_ORDER = 'date';
export const SEARCH_TYPE = 'video';
export const RELEVANCE_LANGUAGE = 'FR';
export const VIDEO_DURATION = 'medium';

export const ARTIST_NAME = [
  // francophones (100)
  'ninho',
  'josman',
  'uzi',
  'la rafleuse',
  'niska',
  'booba',
  'sch',
  'plyne',
  'damso',
  'freeze corleone',
  'tiakola',
  'werenoi',
  'gazo',
  'sdm',
  'jul',
  'plk',
  'leto',
  'nekfeu',
  'orelsan',
  'lomepal',
  'alpha wann',
  'laylow',
  'dinos',
  'vald',
  'kaaris',
  'kalash criminel',
  'kalash',
  'naps',
  'soso maness',
  'koba la d',
  'maes',
  "rim'k",
  '4keus',
  "heuss l'enfoiré",
  'mister you',
  'lacrim',
  'soft',
  'zed',
  'kerchak',
  'winnterzuko',
  'hamza',
  'roméo elvis',
  'caballero',
  'jeanjac',
  'luidji',
  'kronomuzik',
  'soolking',
  'dadju',
  'gims',
  'mhd',
  'naza',
  'hornet la frappe',
  'mmz',
  '13 organise',
  'sadek',
  'alonzo',
  'soprano',
  'iam',
  'oxmo puccino',
  'mc solaar',
  'rohff',
  'la fouine',
  'disiz',
  'youssoupha',
  'médine',
  'kekra',
  'islk',
  'zola',
  'favé',
  'ashe 22',
  'joé dwet filé',
  'timal',
  'pnl',
  'ado',
  'gaulois',
  'menace santana',
  "jok'air",
  'luther',
  'bosh',
  'kofs',
  'shay',
  'guy2bezbar',
  'vacra',
  'jungeli',
  'aminn',
  'genezio',
  'kanoé',
  'dystinct',
  'mok saib',
  'lartiste',
  'keblack',
  'yaro',
  'bolémvn',
  'mig',
  'frojd',
  'bekoko',
  'yung blume',
  'raplume',
  'aya nakamura',
  'ronisia',
  // américains (20)
  'kendrick lamar',
  'drake',
  'j cole',
  'travis scott',
  'future',
  'metro boomin',
  'gunna',
  'lil baby',
  'playboi carti',
  'young thug',
  '21 savage',
  'lil uzi vert',
  'juice wrld',
  'nba youngboy',
  'kodak black',
  'rod wave',
  'polo g',
  'lil durk',
  'offset',
  'don toliver',
];
