export const PAGE_NUMBER = 10;
export const LIMIT_PER_PAGE = 50;
export const IDS_PER_REQUEST = 50;
export const API_URL = 'https://www.googleapis.com/youtube/v3/';

export const SEARCH_ORDER = 'relevance';
export const SEARCH_TYPE = 'video';
export const RELEVANCE_LANGUAGE = 'FR';
export const VIDEO_DURATION = 'medium';

export const ARTIST_NAME = [
  // francophones
  '13 organise',
  '4keus',
  'alonzo',
  'alpha wann',
  'aminn',
  'ashe 22',
  'aya nakamura',
  'bolémvn',
  'booba',
  'bosh',
  'caballero',
  'dadju',
  'damso',
  'dinos',
  'disiz',
  'favé',
  'freeze corleone',
  'gazo',
  'genezio',
  'gims',
  'guy2bezbar',
  'hamza',
  "heuss l'enfoiré",
  'hornet la frappe',
  'isk',
  'joé dwet filé',
  "jok'air",
  'josman',
  'jul',
  'kaaris',
  'kalash',
  'kalash criminel',
  'kanoé',
  'keblack',
  'kekra',
  'kerchak',
  'koba la d',
  'kofs',
  'l2b',
  'la fouine',
  'la rvfleuze',
  'lacrim',
  'lartiste',
  'laylow',
  'leto',
  'lomepal',
  'luidji',
  'luther',
  'maes',
  'mc solaar',
  'médine',
  'menace santana',
  'mhd',
  'mig',
  'mister you',
  'mmz',
  'naps',
  'naza',
  'nekfeu',
  'ninho',
  'niska',
  'orelsan',
  'oxmo puccino',
  'plk',
  'pnl',
  "rim'k",
  'rohff',
  'roméo elvis',
  'ronisia',
  'sadek',
  'sch',
  'sdm',
  'shay',
  'soolking',
  'soprano',
  'soso maness',
  'tiakola',
  'timal',
  'uzi',
  'vacra',
  'vald',
  'werenoi',
  'winnterzuko',
  'yaro',
  'youssoupha',
  'zed',
  'zola',
  // américains (20)
  'kendrick lamar',
  'drake',
  'j cole',
  'travis scott',
  'future',
  'metro boomin',
  'gunna',
  'lil baby',
  'playboi carti',
  'young thug',
  '21 savage',
  'lil uzi vert',
  'juice wrld',
  'nba youngboy',
  'kodak black',
  'rod wave',
  'polo g',
  'lil durk',
  'offset',
  'don toliver',
];
